"""Import existing questions from CSV/JSON/text and validate against PPTX speaker notes or MCP docs."""

import csv
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import List, Optional, Tuple

from .question_bank import Question
from .pptx_reader import PPTXReader, SlideInfo
from . import mcp_client
from ..utils.config import config as _config


def import_from_csv(path: Path) -> List[Question]:
    """Import questions from a CSV file.

    Supports two modes:
    1. **Full round-trip** — CSV exported from this app (all columns preserved).
    2. **Simple import** — minimal columns: Stem, Key, Distractor1-4, plus optional
       Scenario, Explanation, Topic, Difficulty, Bloom.

    Header matching is case-insensitive and tolerates underscores/spaces.
    """
    questions = []
    with open(path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            return []
        # Normalize headers
        header_map = {h.strip().lower().replace(" ", "_"): h for h in reader.fieldnames}

        for row in reader:
            # Helper to get value by fuzzy header match
            def get(candidates, default=""):
                # First pass: exact match on normalized header
                for c in candidates:
                    for key, orig in header_map.items():
                        if c == key:
                            val = row.get(orig, "").strip()
                            if val:
                                return val
                # Second pass: substring match (but require the candidate
                # to match as a whole word boundary to avoid "key" matching "keys")
                for c in candidates:
                    for key, orig in header_map.items():
                        if c in key and c != key:
                            # Avoid substring matches that cross word boundaries
                            # e.g. "key" should not match "keys"
                            import re
                            if re.search(rf'\b{re.escape(c)}\b', key):
                                val = row.get(orig, "").strip()
                                if val:
                                    return val
                return default

            stem = get(["stem", "question"])
            if not stem:
                continue

            key = get(["key_answer", "key", "answer", "correct"])
            distractors = []
            for i in range(1, 5):
                d = get([f"distractor_{i}", f"distractor{i}", f"d{i}", f"wrong_{i}"])
                if d:
                    distractors.append(d)

            # Multi-select: check explicit question_type column, keys column, or | in key
            q_type = get(["question_type"], "single")
            keys_raw = get(["keys"])
            keys_list = []
            if keys_raw:
                keys_list = [k.strip() for k in keys_raw.split("|") if k.strip()]
                if len(keys_list) > 1:
                    q_type = "multi"
                    if not key:
                        key = keys_list[0]
            elif "|" in key:
                keys_list = [k.strip() for k in key.split("|") if k.strip()]
                q_type = "multi"
                key = keys_list[0] if keys_list else ""

            # Parse source_slides (e.g. "1; 3" → [0, 2])
            source_slides_raw = get(["source_slides"])
            source_slides = []
            if source_slides_raw:
                for s in source_slides_raw.replace(";", ",").split(","):
                    s = s.strip()
                    if s.isdigit():
                        source_slides.append(int(s) - 1)  # stored 1-based in CSV

            # Parse key_source_slide (1-based in CSV → 0-based internal)
            key_source_slide_raw = get(["key_source_slide"])
            key_source_slide = -1
            if key_source_slide_raw and key_source_slide_raw.isdigit():
                key_source_slide = int(key_source_slide_raw) - 1

            # Parse tags (semicolon-separated)
            tags_raw = get(["tags"])
            tags = [t.strip() for t in tags_raw.split(";") if t.strip()] if tags_raw else []

            # Status — preserve if valid, otherwise default to draft
            status = get(["status"], "draft").lower()
            from .question_bank import STATUSES
            if status not in STATUSES:
                status = "draft"

            q = Question(
                id=get(["id"], ""),  # empty → auto-generated by Question.__post_init__
                stem=stem,
                question_type=q_type,
                key=key,
                keys=keys_list,
                scenario=get(["scenario", "context"]),
                key_source_text=get(["key_source_text"]),
                distractors=distractors,
                explanation=get(["explanation", "rationale", "feedback"]),
                source_file=get(["source_file"]),
                source_slides=source_slides,
                key_source_slide=key_source_slide,
                topic=get(["topic", "subject", "category"]),
                tags=tags,
                difficulty=get(["difficulty", "level"], "Medium"),
                bloom_level=get(["bloom", "bloom_level", "taxonomy"], "Apply"),
                certification_id=get(["certification_id", "certification"]),
                source_type=get(["source_type"], "pptx"),
                status=status,
                created_by=get(["created_by"], "Import"),
                assigned_sme=get(["assigned_sme"]),
                reject_reason=get(["reject_reason"]),
                created_at=get(["created_at"]),
                reviewed_at=get(["reviewed_at"]),
                approved_at=get(["approved_at"]),
            )
            # Preserve original option order from CSV (option_order column, or build from option_1..N)
            opt_order_raw = get(["option_order"])
            if opt_order_raw:
                q.option_order = [o.strip() for o in opt_order_raw.split("|") if o.strip()]
            else:
                # Try option_1..option_N columns (ordered answers)
                ordered = []
                for i in range(1, 10):
                    o = get([f"option_{i}", f"option{i}", f"choice_{i}", f"choice{i}"])
                    if o:
                        ordered.append(o)
                if ordered:
                    q.option_order = ordered
                else:
                    # Default: keys + distractors as imported
                    q.option_order = q.correct_answers + list(q.distractors)
            questions.append(q)

    return questions


def _is_text_format(path: Path) -> bool:
    """Detect whether a .csv file is actually a text-format question dump
    (no CSV headers, questions separated by blank lines with A:/B:/C: options).
    """
    try:
        with open(path, "r", encoding="utf-8-sig", errors="replace") as f:
            first_lines = []
            for _ in range(10):
                line = f.readline()
                if line == "":
                    break
                first_lines.append(line.strip())
        # A real CSV has commas in the header row. A text dump does not.
        if not first_lines:
            return False
        header = first_lines[0]
        # If the first line has commas, it's likely a real CSV
        if "," in header and any(kw in header.lower() for kw in
                                  ["stem", "question", "key", "answer", "distractor"]):
            return False
        # Check for A:/B:/C: option pattern in the first few lines
        option_pattern = re.compile(r'^[A-E]\s*:\s*$')
        for line in first_lines[1:6]:
            if option_pattern.match(line):
                return True
        return False
    except Exception:
        return False


def import_from_text(path: Path) -> List[Question]:
    """Import questions from a text-format question dump.

    Expected format (questions separated by blank lines)::

        Question stem text? (Choose N.)
        A:
        Option A text
        B:
        Option B text
        C:
        Option C text
        D:
        Option D text
        E:
        Option E text

        Slide N

    Since correct answers are not marked in this format, the first option is
    set as the key and the rest as distractors. Questions are tagged with
    ``key-unverified`` so they can be reviewed and corrected in the app.
    """
    try:
        text = path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError:
        text = path.read_text(encoding="cp1252")
    # Clean up non-breaking spaces and other unicode quirks
    text = text.replace("\u00a0", " ").replace("\ufffd", " ")

    questions: List[Question] = []
    # Split into blocks by blank lines
    blocks = re.split(r'\n\s*\n', text.strip())

    for block in blocks:
        lines = [ln.strip() for ln in block.strip().splitlines() if ln.strip()]
        if not lines:
            continue

        # Standalone "Slide N" blocks → attach to previous question
        if len(lines) == 1 and re.match(r'^Slide\s+(\d+)', lines[0], re.IGNORECASE):
            m = re.match(r'^Slide\s+(\d+)', lines[0], re.IGNORECASE)
            if m and questions:
                slide_idx = int(m.group(1)) - 1
                questions[-1].source_slides = list(set(questions[-1].source_slides + [slide_idx]))
                if questions[-1].key_source_slide < 0:
                    questions[-1].key_source_slide = slide_idx
            continue

        # First line is the stem
        stem = lines[0]
        if not stem or len(stem) < 5:
            continue

        # Parse options (A: ... B: ... etc.)
        options: dict = {}
        current_letter = None
        slide_ref = ""
        remaining_lines = lines[1:]

        for line in remaining_lines:
            # Check for "Slide N" reference
            slide_match = re.match(r'^Slide\s+(\d+)', line, re.IGNORECASE)
            if slide_match:
                slide_ref = slide_match.group(1)
                continue

            # Check for option letter (A: or A: text on same line)
            opt_match = re.match(r'^([A-E])\s*:\s*(.*)', line, re.IGNORECASE)
            if opt_match:
                current_letter = opt_match.group(1).upper()
                rest = opt_match.group(2).strip()
                if rest:
                    options[current_letter] = rest
                else:
                    options[current_letter] = ""
            elif current_letter and current_letter in options and not options[current_letter]:
                # This line is the option text for the current letter
                options[current_letter] = line
            elif current_letter and current_letter in options:
                # Continuation of current option text
                options[current_letter] += " " + line

        if not options:
            continue

        # Detect multi-select from stem
        num_correct = 1
        choose_match = re.search(r'\((?:Choose|Select)\s+(two|three|four|five|\d+)', stem, re.IGNORECASE)
        if choose_match:
            word_map = {"two": 2, "three": 3, "four": 4, "five": 5}
            val = choose_match.group(1).lower()
            num_correct = word_map.get(val, int(val) if val.isdigit() else 1)

        option_list = list(options.values())
        q_type = "multi" if num_correct > 1 else "single"

        # Text format doesn't mark correct answers.
        # For single-select: assume first option as key (tagged key-unverified).
        # For multi-select: we CAN'T guess which N are correct, so set ALL
        # options as distractors and leave key empty — user must assign manually.
        if q_type == "multi":
            keys = []
            distractors = option_list
        else:
            keys = option_list[:1]
            distractors = option_list[1:]

        # Parse source slide
        source_slides = []
        key_source_slide = -1
        if slide_ref and slide_ref.isdigit():
            slide_idx = int(slide_ref) - 1  # 0-based
            source_slides = [slide_idx]
            key_source_slide = slide_idx

        q = Question(
            stem=stem,
            question_type=q_type,
            key=keys[0] if keys else "",
            keys=keys if q_type == "multi" else [],
            distractors=distractors,
            option_order=option_list,  # preserve original A,B,C,D,E order
            source_slides=source_slides,
            key_source_slide=key_source_slide,
            difficulty="Medium",
            bloom_level="Apply",
            status="draft",
            created_by="Import",
            tags=["key-unverified"],
        )
        questions.append(q)

    return questions


def import_from_json(path: Path) -> List[Question]:
    """Import questions from a JSON array file.

    Each element should have: stem, key (or keys for multi), distractors, etc.
    """
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        return []

    questions = []
    for item in data:
        if not isinstance(item, dict):
            continue
        q_type = item.get("question_type", "single")
        keys_list = item.get("keys", [])
        key = item.get("key", "")
        if q_type == "multi" and not keys_list and "|" in key:
            keys_list = [k.strip() for k in key.split("|")]
            key = keys_list[0] if keys_list else ""

        dists = item.get("distractors", [])
        opt_order = item.get("option_order", [])
        if not opt_order:
            # Build from keys + distractors
            ca = keys_list if keys_list else ([key] if key else [])
            opt_order = ca + dists
        q = Question(
            stem=item.get("stem", ""),
            question_type=q_type,
            key=key,
            keys=keys_list,
            scenario=item.get("scenario", ""),
            distractors=dists,
            option_order=opt_order,
            explanation=item.get("explanation", ""),
            topic=item.get("topic", ""),
            difficulty=item.get("difficulty", "Medium"),
            bloom_level=item.get("bloom_level", "Apply"),
            key_source_text=item.get("key_source_text", ""),
            status="draft",
            created_by="Import",
        )
        questions.append(q)

    return questions


def _strip_html(text: str) -> str:
    """Simple HTML tag stripper for Moodle content."""
    return re.sub(r'<[^>]+>', '', text or "").strip()


def detect_xml_format(path: Path) -> str:
    """Return 'qti', 'moodle', or 'unknown'."""
    tree = ET.parse(path)
    root = tree.getroot()
    tag = root.tag.lower()
    if 'assessmenttest' in tag or 'assessmentitem' in tag:
        return 'qti'
    if root.tag == 'quiz' or (root.tag == 'question' and root.get('type')):
        return 'moodle'
    return 'unknown'


def import_from_qti21(path: Path) -> List[Question]:
    """Import questions from a QTI 2.1 XML file.

    Supports the QTI 2.1 format exported by this app:
    - Root: <assessmentTest> with <testPart> > <assessmentSection> > <assessmentItem>
    - Each item has responseDeclaration, itemBody with choiceInteraction.
    """
    tree = ET.parse(path)
    root = tree.getroot()

    # Handle QTI namespace: try with namespace and without
    ns = {'qti': 'http://www.imsglobal.org/xsd/imsqti_v2p1'}

    def _find_all(parent, tag):
        """Find elements trying with namespace first, then without."""
        results = parent.findall(f'.//qti:{tag}', ns)
        if not results:
            results = parent.findall(f'.//{tag}')
        return results

    def _find(parent, tag):
        """Find single element trying with namespace first, then without."""
        result = parent.find(f'.//qti:{tag}', ns)
        if result is None:
            result = parent.find(f'.//{tag}')
        return result

    questions = []
    items = _find_all(root, 'assessmentItem')

    for item in items:
        # Get correct answer identifier from responseDeclaration
        resp_decl = _find(item, 'responseDeclaration')
        correct_id = ""
        if resp_decl is not None:
            correct_value = _find(resp_decl, 'value')
            if correct_value is not None and correct_value.text:
                correct_id = correct_value.text.strip()

        # Get prompt (stem) from choiceInteraction
        prompt_elem = _find(item, 'prompt')
        stem = ""
        if prompt_elem is not None and prompt_elem.text:
            stem = prompt_elem.text.strip()

        if not stem:
            continue

        # Get all simpleChoice elements
        choices = _find_all(item, 'simpleChoice')
        key = ""
        distractors = []
        option_order = []

        for choice in choices:
            identifier = choice.get('identifier', '')
            text = (choice.text or '').strip()
            option_order.append(text)
            if identifier == correct_id:
                key = text
            else:
                distractors.append(text)

        if not key and not distractors:
            continue

        q = Question(
            stem=stem,
            key=key,
            distractors=distractors,
            option_order=option_order,
            difficulty="Medium",
            bloom_level="Apply",
            status="draft",
            created_by="Import",
        )
        questions.append(q)

    return questions


def import_from_moodle_xml(path: Path) -> List[Question]:
    """Import questions from a Moodle XML file.

    Supports the Moodle XML format exported by this app:
    - Root: <quiz> > <question type="multichoice">
    - Each question has questiontext, answers with fractions, generalfeedback, tags.
    """
    tree = ET.parse(path)
    root = tree.getroot()

    questions = []

    # Find all multichoice question elements
    for q_elem in root.findall('.//question[@type="multichoice"]'):
        # Extract stem from questiontext (strip HTML tags)
        stem = ""
        qt_elem = q_elem.find('questiontext')
        if qt_elem is not None:
            text_elem = qt_elem.find('text')
            if text_elem is not None and text_elem.text:
                stem = _strip_html(text_elem.text)

        if not stem:
            continue

        # Extract answers by fraction
        key = ""
        distractors = []
        option_order = []

        for ans_elem in q_elem.findall('answer'):
            fraction = ans_elem.get('fraction', '0')
            text_elem = ans_elem.find('text')
            text = _strip_html(text_elem.text) if text_elem is not None else ""
            if not text:
                continue
            option_order.append(text)
            try:
                frac_val = float(fraction)
            except (ValueError, TypeError):
                frac_val = 0.0
            if frac_val > 0:
                if not key:
                    key = text
                # For multi-select support in the future, additional keys
                # could be tracked here
            else:
                distractors.append(text)

        if not key and not distractors:
            continue

        # Extract explanation from generalfeedback
        explanation = ""
        gf_elem = q_elem.find('generalfeedback')
        if gf_elem is not None:
            gf_text = gf_elem.find('text')
            if gf_text is not None and gf_text.text:
                explanation = _strip_html(gf_text.text)

        # Extract topic from tags
        topic = ""
        tags_elem = q_elem.find('tags')
        if tags_elem is not None:
            tag_elem = tags_elem.find('tag')
            if tag_elem is not None:
                tag_text = tag_elem.find('text')
                if tag_text is not None and tag_text.text:
                    topic = tag_text.text.strip()

        q = Question(
            stem=stem,
            key=key,
            distractors=distractors,
            option_order=option_order,
            explanation=explanation,
            topic=topic,
            difficulty="Medium",
            bloom_level="Apply",
            status="draft",
            created_by="Import",
        )
        questions.append(q)

    return questions


def _match_option_to_notes(option: str, norm_ref: str) -> float:
    """Score how well a single option matches the reference text (0.0-1.0).

    Returns 1.0 for exact substring match, otherwise word overlap ratio.
    """
    norm_opt = " ".join(option.lower().split())
    if not norm_opt:
        return 0.0
    if norm_opt in norm_ref:
        return 1.0
    opt_words = set(norm_opt.split())
    ref_words = set(norm_ref.split())
    if not opt_words:
        return 0.0
    return len(opt_words & ref_words) / len(opt_words)


def _get_slide_reference(question: "Question", reader: PPTXReader):
    """Get the reference text (speaker notes or body) from the question's source slide.

    Returns (reference_text, slide_index, source_label) or ("", -1, "") if none.
    """
    # Prioritize: key_source_slide, then source_slides, then search all
    candidates = []
    if question.key_source_slide >= 0:
        candidates.append(question.key_source_slide)
    for s in question.source_slides:
        if s not in candidates:
            candidates.append(s)

    for idx in candidates:
        if 0 <= idx < reader.slide_count:
            slide = reader.slides[idx]
            notes = slide.speaker_notes.strip() if slide.speaker_notes else ""
            body = slide.body_text or ""
            ref = notes if notes else body
            if ref:
                label = "speaker notes" if notes else "body text"
                return ref, idx, label
    return "", -1, ""


def validate_question_against_pptx(
    question: Question,
    reader: PPTXReader,
    source_file: str = "",
) -> Tuple[bool, str, int, str]:
    """Validate a question's answers against PPTX speaker notes.

    Two modes:
    1. **Key-unverified** (text-format imports with no keys assigned):
       Check ALL options against the referenced slide's notes to determine
       which are keys (supported by notes) and which are distractors.
    2. **Normal** (keys already assigned):
       Verify the correct answer(s) appear in speaker notes.

    Returns:
        (passed, match_text, slide_index, details)
    """
    if not reader or reader.slide_count == 0:
        return False, "", -1, "No PPTX loaded"

    def normalize(s):
        return " ".join(s.lower().split())

    needs_key_assignment = (
        "key-unverified" in question.tags
        and not question.correct_answers
        and question.distractors
    )

    # ── Mode 1: Assign keys from notes (unverified multi-select) ────────
    if needs_key_assignment:
        ref_text, slide_idx, source_label = _get_slide_reference(question, reader)

        # If no referenced slide, search all slides for the best one
        if not ref_text:
            best_slide_idx = -1
            best_total_score = 0.0
            for slide in reader.slides:
                notes = slide.speaker_notes.strip() if slide.speaker_notes else ""
                body = slide.body_text or ""
                ref = notes if notes else body
                if not ref:
                    continue
                norm_ref = normalize(ref)
                total = sum(
                    _match_option_to_notes(opt, norm_ref)
                    for opt in question.distractors
                )
                if total > best_total_score:
                    best_total_score = total
                    best_slide_idx = slide.index
                    ref_text = ref
                    source_label = "speaker notes" if notes else "body text"
            slide_idx = best_slide_idx

        if not ref_text:
            return False, "", -1, "No speaker notes found in any slide"

        norm_ref = normalize(ref_text)

        # Score each option against the notes
        scored = []
        for opt in question.distractors:
            score = _match_option_to_notes(opt, norm_ref)
            scored.append((opt, score))

        # Determine how many keys we expect from the stem
        num_expected = 1
        import re as _re
        choose_match = _re.search(
            r'(?:Choose|Select|Which)\s+(two|three|four|five|\d+)',
            question.stem, _re.IGNORECASE,
        )
        if choose_match:
            word_map = {"two": 2, "three": 3, "four": 4, "five": 5}
            val = choose_match.group(1).lower()
            num_expected = word_map.get(val, int(val) if val.isdigit() else 1)

        # Sort by score descending, take the top N as keys
        scored.sort(key=lambda x: x[1], reverse=True)
        threshold = _config.validation_threshold
        new_keys = []
        new_distractors = []
        for opt, score in scored:
            if len(new_keys) < num_expected and score >= threshold:
                new_keys.append(opt)
            else:
                new_distractors.append(opt)

        if not new_keys:
            # No option matched well enough
            best_score = scored[0][1] if scored else 0
            return False, "", slide_idx, (
                f"No options matched notes (best: {best_score:.0%} overlap) "
                f"in slide {slide_idx + 1} {source_label}"
            )

        # Assign keys and distractors
        question.key = new_keys[0]
        if len(new_keys) > 1:
            question.keys = new_keys
            question.question_type = "multi"
        else:
            question.keys = []
            question.question_type = "single"
        question.distractors = new_distractors
        question.key_source_slide = slide_idx
        question.source_slides = list(set(question.source_slides + [slide_idx]))
        question.source_file = source_file
        question.key_source_text = new_keys[0]
        # Remove the unverified tag — keys are now assigned from notes
        question.tags = [t for t in question.tags if t != "key-unverified"]

        key_scores = [f"'{k}' ({s:.0%})" for k, s in scored if k in new_keys]
        return True, question.key, slide_idx, (
            f"Assigned {len(new_keys)} key(s) from slide {slide_idx + 1} {source_label}: "
            + ", ".join(key_scores)
        )

    # ── Mode 2: Validate existing keys against notes ────────────────────
    answers_to_check = question.correct_answers
    if not answers_to_check:
        return False, "", -1, "No correct answer to validate"

    # Priority 1: Check referenced slide(s) first
    ref_text, ref_slide, ref_label = _get_slide_reference(question, reader)
    if ref_text:
        norm_ref = normalize(ref_text)
        for answer in answers_to_check:
            if _match_option_to_notes(answer, norm_ref) >= 1.0:
                question.key_source_text = answer
                question.key_source_slide = ref_slide
                question.source_slides = list(set(question.source_slides + [ref_slide]))
                question.source_file = source_file
                return True, answer, ref_slide, (
                    f"Exact match in slide {ref_slide + 1} {ref_label}"
                )
        # Fuzzy on referenced slide
        best_ov = max(
            _match_option_to_notes(a, norm_ref) for a in answers_to_check
        )
        if best_ov >= _config.validation_threshold:
            question.key_source_slide = ref_slide
            question.source_slides = list(set(question.source_slides + [ref_slide]))
            question.source_file = source_file
            return True, "", ref_slide, (
                f"Fuzzy match ({best_ov:.0%} overlap) in slide {ref_slide + 1} {ref_label}"
            )

    # Priority 2: Search all other slides
    referenced = set(question.source_slides)
    if question.key_source_slide >= 0:
        referenced.add(question.key_source_slide)

    best_overlap = 0.0
    best_slide = -1
    best_match = ""

    for slide in reader.slides:
        if slide.index in referenced and ref_text:
            continue  # already checked
        notes = slide.speaker_notes.strip() if slide.speaker_notes else ""
        body = slide.body_text or ""
        reference = notes if notes else body
        if not reference:
            continue
        norm_r = normalize(reference)

        for answer in answers_to_check:
            score = _match_option_to_notes(answer, norm_r)
            if score >= 1.0:
                question.key_source_text = answer
                question.key_source_slide = slide.index
                question.source_slides = list(set(question.source_slides + [slide.index]))
                question.source_file = source_file
                label = "speaker notes" if notes else "body text"
                return True, answer, slide.index, (
                    f"Exact match in slide {slide.index + 1} {label}"
                )
            if score > best_overlap:
                best_overlap = score
                best_slide = slide.index
                best_match = answer

    if best_overlap >= _config.validation_threshold:
        question.key_source_slide = best_slide
        question.source_slides = list(set(question.source_slides + [best_slide]))
        question.source_file = source_file
        question.key_source_text = best_match
        return True, best_match, best_slide, (
            f"Fuzzy match ({best_overlap:.0%} overlap) in slide {best_slide + 1}"
        )

    detail = f"No match found (best: {best_overlap:.0%} overlap"
    if best_slide >= 0:
        detail += f" in slide {best_slide + 1}"
    detail += ")"
    return False, "", -1, detail


def validate_batch(
    questions: List[Question],
    reader: PPTXReader,
    source_file: str = "",
) -> List[Tuple[Question, bool, str]]:
    """Validate a batch of questions against a PPTX.

    Returns list of (question, passed, details) tuples.
    """
    results = []
    for q in questions:
        passed, match_text, slide_idx, details = validate_question_against_pptx(
            q, reader, source_file
        )
        if passed:
            # Remove unverified/not-validated tags on success
            q.tags = [t for t in q.tags if t not in ("key-not-validated", "key-unverified")]
        else:
            # Mark as failed validation
            q.tags = [t for t in q.tags if t not in ("key-not-validated", "key-unverified")]
            q.tags.append("key-not-validated")
        results.append((q, passed, details))
    return results


def validate_question_against_docs(
    question: Question,
    servers: list,
) -> Tuple[bool, str, str]:
    """Validate a question's key against MCP documentation servers.

    Searches configured MCP servers for the question stem + key and checks
    whether the documentation supports the correct answer.

    Args:
        question: The question to validate.
        servers: List of MCP server dicts [{"name": ..., "url": ...}, ...].

    Returns:
        (passed, match_text, details)
        - passed: True if key text was found in documentation
        - match_text: the matching snippet from docs
        - details: human-readable validation result
    """
    if not servers:
        return False, "", "No MCP servers configured"

    answers_to_check = question.correct_answers
    if not answers_to_check:
        return False, "", "No correct answer to validate"

    def normalize(s):
        return " ".join(s.lower().split())

    # Search docs using the stem as query (most relevant context)
    search_query = question.stem[:200]
    try:
        doc_text = mcp_client.search_multiple_servers(
            search_query, servers, max_results=6, max_chars=5000
        )
    except Exception as ex:
        return False, "", f"MCP search failed: {ex}"

    if not doc_text:
        return False, "", "No documentation found for this question"

    norm_docs = normalize(doc_text)

    best_overlap = 0.0
    best_answer = ""
    best_match = ""

    for answer in answers_to_check:
        norm_ans = normalize(answer)
        if not norm_ans:
            continue

        # Exact substring match
        if norm_ans in norm_docs:
            question.key_source_text = answer
            return True, answer, "Exact match found in documentation"

        # Fuzzy word overlap
        ans_words = set(norm_ans.split())
        doc_words = set(norm_docs.split())
        if ans_words:
            overlap = len(ans_words & doc_words) / len(ans_words)
            if overlap > best_overlap:
                best_overlap = overlap
                best_answer = answer
                matched_words = ans_words & doc_words
                best_match = " ".join(sorted(matched_words))

    # Accept if 70%+ word overlap
    if best_overlap >= _config.validation_threshold:
        question.key_source_text = best_match
        return True, best_match, f"Fuzzy match ({best_overlap:.0%} overlap) in documentation"

    detail = f"No match found in docs (best: {best_overlap:.0%} overlap)"
    return False, "", detail
