"""Import existing questions from CSV/JSON/text and validate against PPTX speaker notes or MCP docs."""

import csv
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import List, Optional, Tuple

from .bank import BLOOM_LEVELS, Question
from .pcm_reader import read_course_json
from .source import SlideInfo
from ..utils.config import config as _config


def import_from_csv(path: Path) -> List[Question]:
    """Import questions from a CSV file.

    Supports two modes:
    1. **Full round-trip** — CSV exported from this app (all columns preserved).
    2. **Simple import** — minimal columns: Stem, Key, Distractor1-4, plus optional
       Scenario, Explanation, Topic, Difficulty, Bloom.

    Header matching is case-insensitive and tolerates underscores/spaces.
    """
    questions = []
    with open(path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            return []
        # Normalize headers
        header_map = {h.strip().lower().replace(" ", "_"): h for h in reader.fieldnames}

        for row in reader:
            # Helper to get value by fuzzy header match
            def get(candidates, default=""):
                # First pass: exact match on normalized header
                for c in candidates:
                    for key, orig in header_map.items():
                        if c == key:
                            val = row.get(orig, "").strip()
                            if val:
                                return val
                # Second pass: substring match (but require the candidate
                # to match as a whole word boundary to avoid "key" matching "keys")
                for c in candidates:
                    for key, orig in header_map.items():
                        if c in key and c != key:
                            # Avoid substring matches that cross word boundaries
                            # e.g. "key" should not match "keys"
                            import re
                            if re.search(rf'\b{re.escape(c)}\b', key):
                                val = row.get(orig, "").strip()
                                if val:
                                    return val
                return default

            stem = get(["stem", "question"])
            if not stem:
                continue

            key = get(["key_answer", "key", "answer", "correct"])
            distractors = []
            for i in range(1, 5):
                d = get([f"distractor_{i}", f"distractor{i}", f"d{i}", f"wrong_{i}"])
                if d:
                    distractors.append(d)

            # Multi-select: check explicit question_type column, keys column, or | in key
            q_type = get(["question_type"], "single")
            keys_raw = get(["keys"])
            keys_list = []
            if keys_raw:
                keys_list = [k.strip() for k in keys_raw.split("|") if k.strip()]
                if len(keys_list) > 1:
                    q_type = "multi"
                    if not key:
                        key = keys_list[0]
            elif "|" in key:
                keys_list = [k.strip() for k in key.split("|") if k.strip()]
                q_type = "multi"
                key = keys_list[0] if keys_list else ""

            # Parse source_slides (e.g. "1; 3" → [0, 2])
            source_slides_raw = get(["source_slides"])
            source_slides = []
            if source_slides_raw:
                for s in source_slides_raw.replace(";", ",").split(","):
                    s = s.strip()
                    if s.isdigit():
                        source_slides.append(int(s) - 1)  # stored 1-based in CSV

            # Parse key_source_slide (1-based in CSV → 0-based internal)
            key_source_slide_raw = get(["key_source_slide"])
            key_source_slide = -1
            if key_source_slide_raw and key_source_slide_raw.isdigit():
                key_source_slide = int(key_source_slide_raw) - 1

            # Parse tags (semicolon-separated)
            tags_raw = get(["tags"])
            tags = [t.strip() for t in tags_raw.split(";") if t.strip()] if tags_raw else []

            # Status — preserve if valid, otherwise default to draft
            status = get(["status"], "draft").lower()
            from .bank import STATUSES
            if status not in STATUSES:
                status = "draft"

            q = Question(
                id=get(["id"], ""),  # empty → auto-generated by Question.__post_init__
                stem=stem,
                question_type=q_type,
                key=key,
                keys=keys_list,
                scenario=get(["scenario", "context"]),
                key_source_text=get(["key_source_text"]),
                distractors=distractors,
                explanation=get(["explanation", "rationale", "feedback"]),
                source_file=get(["source_file"]),
                source_slides=source_slides,
                key_source_slide=key_source_slide,
                topic=get(["topic", "subject", "category"]),
                tags=tags,
                difficulty=get(["difficulty", "level"], "Medium"),
                bloom_level=_bloom_of({k: get([k]) for k in _BLOOM_KEYS}),
                certification_id=get(["certification_id", "certification"]),
                source_type=get(["source_type"], "pptx"),
                status=status,
                created_by=get(["created_by"], "Import"),
                assigned_sme=get(["assigned_sme"]),
                reject_reason=get(["reject_reason"]),
                created_at=get(["created_at"]),
                reviewed_at=get(["reviewed_at"]),
                approved_at=get(["approved_at"]),
            )
            # Preserve original option order from CSV (option_order column, or build from option_1..N)
            opt_order_raw = get(["option_order"])
            if opt_order_raw:
                q.option_order = [o.strip() for o in opt_order_raw.split("|") if o.strip()]
            else:
                # Try option_1..option_N columns (ordered answers)
                ordered = []
                for i in range(1, 10):
                    o = get([f"option_{i}", f"option{i}", f"choice_{i}", f"choice{i}"])
                    if o:
                        ordered.append(o)
                if ordered:
                    q.option_order = ordered
                else:
                    # Default: keys + distractors as imported
                    q.option_order = q.correct_answers + list(q.distractors)
            questions.append(q)

    return questions


def _is_text_format(path: Path) -> bool:
    """Detect whether a .csv file is actually a text-format question dump
    (no CSV headers, questions separated by blank lines with A:/B:/C: options).
    """
    try:
        with open(path, "r", encoding="utf-8-sig", errors="replace") as f:
            first_lines = []
            for _ in range(10):
                line = f.readline()
                if line == "":
                    break
                first_lines.append(line.strip())
        # A real CSV has commas in the header row. A text dump does not.
        if not first_lines:
            return False
        header = first_lines[0]
        # If the first line has commas, it's likely a real CSV
        if "," in header and any(kw in header.lower() for kw in
                                  ["stem", "question", "key", "answer", "distractor"]):
            return False
        # Check for A:/B:/C: option pattern in the first few lines
        option_pattern = re.compile(r'^[A-E]\s*:\s*$')
        for line in first_lines[1:6]:
            if option_pattern.match(line):
                return True
        return False
    except Exception:
        return False


def import_from_text(path: Path) -> List[Question]:
    """Import questions from a text-format question dump.

    Expected format (questions separated by blank lines)::

        Question stem text? (Choose N.)
        A:
        Option A text
        B:
        Option B text
        C:
        Option C text
        D:
        Option D text
        E:
        Option E text

        Slide N

    Since correct answers are not marked in this format, the first option is
    set as the key and the rest as distractors. Questions are tagged with
    ``key-unverified`` so they can be reviewed and corrected in the app.
    """
    try:
        text = path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError:
        text = path.read_text(encoding="cp1252")
    # Clean up non-breaking spaces and other unicode quirks
    text = text.replace("\u00a0", " ").replace("\ufffd", " ")

    questions: List[Question] = []
    # Split into blocks by blank lines
    blocks = re.split(r'\n\s*\n', text.strip())

    for block in blocks:
        lines = [ln.strip() for ln in block.strip().splitlines() if ln.strip()]
        if not lines:
            continue

        # Standalone "Slide N" blocks → attach to previous question
        if len(lines) == 1 and re.match(r'^Slide\s+(\d+)', lines[0], re.IGNORECASE):
            m = re.match(r'^Slide\s+(\d+)', lines[0], re.IGNORECASE)
            if m and questions:
                slide_idx = int(m.group(1)) - 1
                questions[-1].source_slides = list(set(questions[-1].source_slides + [slide_idx]))
                if questions[-1].key_source_slide < 0:
                    questions[-1].key_source_slide = slide_idx
            continue

        # First line is the stem
        stem = lines[0]
        if not stem or len(stem) < 5:
            continue

        # Parse options (A: ... B: ... etc.)
        options: dict = {}
        current_letter = None
        slide_ref = ""
        remaining_lines = lines[1:]

        for line in remaining_lines:
            # Check for "Slide N" reference
            slide_match = re.match(r'^Slide\s+(\d+)', line, re.IGNORECASE)
            if slide_match:
                slide_ref = slide_match.group(1)
                continue

            # Check for option letter (A: or A: text on same line)
            opt_match = re.match(r'^([A-E])\s*:\s*(.*)', line, re.IGNORECASE)
            if opt_match:
                current_letter = opt_match.group(1).upper()
                rest = opt_match.group(2).strip()
                if rest:
                    options[current_letter] = rest
                else:
                    options[current_letter] = ""
            elif current_letter and current_letter in options and not options[current_letter]:
                # This line is the option text for the current letter
                options[current_letter] = line
            elif current_letter and current_letter in options:
                # Continuation of current option text
                options[current_letter] += " " + line

        if not options:
            continue

        # Detect multi-select from stem
        num_correct = 1
        choose_match = re.search(r'\((?:Choose|Select)\s+(two|three|four|five|\d+)', stem, re.IGNORECASE)
        if choose_match:
            word_map = {"two": 2, "three": 3, "four": 4, "five": 5}
            val = choose_match.group(1).lower()
            num_correct = word_map.get(val, int(val) if val.isdigit() else 1)

        option_list = list(options.values())
        q_type = "multi" if num_correct > 1 else "single"

        # Text format doesn't mark correct answers.
        # For single-select: assume first option as key (tagged key-unverified).
        # For multi-select: we CAN'T guess which N are correct, so set ALL
        # options as distractors and leave key empty — user must assign manually.
        if q_type == "multi":
            keys = []
            distractors = option_list
        else:
            keys = option_list[:1]
            distractors = option_list[1:]

        # Parse source slide
        source_slides = []
        key_source_slide = -1
        if slide_ref and slide_ref.isdigit():
            slide_idx = int(slide_ref) - 1  # 0-based
            source_slides = [slide_idx]
            key_source_slide = slide_idx

        q = Question(
            stem=stem,
            question_type=q_type,
            key=keys[0] if keys else "",
            keys=keys if q_type == "multi" else [],
            distractors=distractors,
            option_order=option_list,  # preserve original A,B,C,D,E order
            source_slides=source_slides,
            key_source_slide=key_source_slide,
            difficulty="Medium",
            bloom_level="Understand",
            status="draft",
            created_by="Import",
            tags=["key-unverified"],
        )
        questions.append(q)

    return questions


def import_from_json(path: Path) -> List[Question]:
    """Import questions from a JSON array file.

    Each element should have: stem, key (or keys for multi), distractors, etc.
    """
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, list):
        return []

    questions = []
    for item in data:
        if not isinstance(item, dict):
            continue
        q_type = item.get("question_type", "single")
        keys_list = item.get("keys", [])
        key = item.get("key", "")
        if q_type == "multi" and not keys_list and "|" in key:
            keys_list = [k.strip() for k in key.split("|")]
            key = keys_list[0] if keys_list else ""

        dists = item.get("distractors", [])
        opt_order = item.get("option_order", [])
        if not opt_order:
            # Build from keys + distractors
            ca = keys_list if keys_list else ([key] if key else [])
            opt_order = ca + dists
        q = Question(
            stem=item.get("stem", ""),
            question_type=q_type,
            key=key,
            keys=keys_list,
            scenario=item.get("scenario", ""),
            distractors=dists,
            option_order=opt_order,
            explanation=item.get("explanation", ""),
            topic=item.get("topic", ""),
            difficulty=item.get("difficulty", "Medium"),
            bloom_level=_bloom_of(item),
            key_source_text=item.get("key_source_text", ""),
            status="draft",
            created_by="Import",
        )
        questions.append(q)

    return questions


def is_pcm_exam_json(path: Path) -> bool:
    """True when a .json file is a PCM ``exam.json`` rather than a bank export.

    A PCM exam is an object with a ``questions`` array whose items use
    ``prompt``/``options`` (vs the bank's top-level array of ``stem``/``key``).
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except Exception:
        return False
    if not isinstance(data, dict):
        return False
    qs = data.get("questions")
    if not isinstance(qs, list) or not qs:
        return False
    first = qs[0]
    return isinstance(first, dict) and "prompt" in first and "options" in first


#: The spellings a source may use. `bloom` is what a PCM exam.json writes,
#: `bloom_level` what this app's own CSV and JSON exports write, and
#: `taxonomy` what several other question-bank tools call it.
_BLOOM_KEYS = ("bloom", "bloom_level", "taxonomy")


def _bloom_of(item: dict) -> str:
    """The Bloom level a question states, or the default.

    Shared by the PCM, CSV and JSON importers so that all three accept the
    same spellings, match case-insensitively, and refuse anything outside
    BLOOM_LEVELS rather than writing it through. A bloom_level the bank's
    own editor would reject is worse than the default, because it looks
    deliberate.

    CSV read the three spellings but neither normalised case nor validated,
    so a file saying `apply` wrote `apply` into the column. JSON read only
    `bloom_level`, so a file using `bloom` - the spelling CSV accepts and
    PCM writes - silently got the default.
    """
    for key in _BLOOM_KEYS:
        value = str(item.get(key) or "").strip()
        if value:
            for level in BLOOM_LEVELS:
                if value.lower() == level.lower():
                    return level
    return "Understand"


def import_from_pcm_exam_json(path: Path) -> List[Question]:
    """Import questions from a Pentaho Content Manager ``exam.json``.

    The inverse of ``exporter.export_pcm_exam_json``: each item's ``options``
    are split into key(s) + distractors using ``correct``/``correctIndices``,
    ``prompt`` becomes the stem, and ``module`` becomes the topic. Imported
    questions are tagged as the ``pcm`` source and land as drafts.
    """
    data = read_course_json(path)
    if not isinstance(data, dict):
        return []
    exam_title = str(data.get("title") or "").strip()

    questions = []
    for position, item in enumerate(data.get("questions", [])):
        if not isinstance(item, dict):
            continue
        options = [str(o) for o in item.get("options", []) if isinstance(o, (str, int, float))]
        if not options:
            continue

        # Resolve correct indices: correctIndices (multi) wins, else correct (single).
        idxs = item.get("correctIndices")
        if isinstance(idxs, list) and idxs:
            correct_idx = [i for i in idxs if isinstance(i, int) and 0 <= i < len(options)]
        else:
            c = item.get("correct")
            correct_idx = [c] if isinstance(c, int) and 0 <= c < len(options) else []

        keys_list = [options[i] for i in correct_idx]
        distractors = [o for j, o in enumerate(options) if j not in set(correct_idx)]
        is_multi = len(keys_list) > 1

        q = Question(
            # Carry the authored id through. PCM treats it as a durable
            # external key: it goes into the results payload the webhook
            # posts to the Sheet, and an in-progress attempt is keyed on
            # the question ids it was dealt. Minting a fresh uuid here
            # would orphan every result already recorded against this
            # pool. Question.__post_init__ still mints one when the
            # source genuinely has no id — PCM's own fallback for that
            # case is POSITIONAL (`q1`, `q2`, ...), so an id must never
            # be allowed to depend on a question's place in the list.
            id=str(item.get("id") or "").strip(),
            # Remember where it sat in the pool, so publishing back writes
            # the array in the author's order instead of whatever order the
            # bank happened to return.
            pool_order=position,
            stem=item.get("prompt", ""),
            question_type="multi" if is_multi else "single",
            key=keys_list[0] if keys_list else "",
            keys=keys_list if is_multi else [],
            scenario=item.get("scenario", ""),
            distractors=distractors,
            option_order=list(options),                 # preserve authored order
            explanation=item.get("explanation", ""),
            topic=item.get("module", "") or exam_title,
            # A PCM course may state the level it was judged at. Honour it:
            # this path used to hardcode the default, so a course that had
            # been classified question-by-question arrived flattened to a
            # single level, and re-syncing an edited course silently undid
            # the classification. Fall back to the same defaults as before
            # when the course says nothing.
            difficulty=str(item.get("difficulty") or "Medium"),
            bloom_level=_bloom_of(item),
            source_type="pcm",
            source_file=str(item.get("source", "")),
            status="draft",
            created_by="Import",
        )
        questions.append(q)

    return questions


def _strip_html(text: str) -> str:
    """Simple HTML tag stripper for Moodle content."""
    return re.sub(r'<[^>]+>', '', text or "").strip()


def detect_xml_format(path: Path) -> str:
    """Return 'qti', 'moodle', or 'unknown'."""
    tree = ET.parse(path)
    root = tree.getroot()
    tag = root.tag.lower()
    if 'assessmenttest' in tag or 'assessmentitem' in tag:
        return 'qti'
    if root.tag == 'quiz' or (root.tag == 'question' and root.get('type')):
        return 'moodle'
    return 'unknown'


def import_from_qti21(path: Path) -> List[Question]:
    """Import questions from a QTI 2.1 XML file.

    Supports the QTI 2.1 format exported by this app:
    - Root: <assessmentTest> with <testPart> > <assessmentSection> > <assessmentItem>
    - Each item has responseDeclaration, itemBody with choiceInteraction.
    """
    tree = ET.parse(path)
    root = tree.getroot()

    # Handle QTI namespace: try with namespace and without
    ns = {'qti': 'http://www.imsglobal.org/xsd/imsqti_v2p1'}

    def _find_all(parent, tag):
        """Find elements trying with namespace first, then without."""
        results = parent.findall(f'.//qti:{tag}', ns)
        if not results:
            results = parent.findall(f'.//{tag}')
        return results

    def _find(parent, tag):
        """Find single element trying with namespace first, then without."""
        result = parent.find(f'.//qti:{tag}', ns)
        if result is None:
            result = parent.find(f'.//{tag}')
        return result

    questions = []
    items = _find_all(root, 'assessmentItem')

    for item in items:
        # Get correct answer identifier from responseDeclaration
        resp_decl = _find(item, 'responseDeclaration')
        correct_id = ""
        if resp_decl is not None:
            correct_value = _find(resp_decl, 'value')
            if correct_value is not None and correct_value.text:
                correct_id = correct_value.text.strip()

        # Get prompt (stem) from choiceInteraction
        prompt_elem = _find(item, 'prompt')
        stem = ""
        if prompt_elem is not None and prompt_elem.text:
            stem = prompt_elem.text.strip()

        if not stem:
            continue

        # Get all simpleChoice elements
        choices = _find_all(item, 'simpleChoice')
        key = ""
        distractors = []
        option_order = []

        for choice in choices:
            identifier = choice.get('identifier', '')
            text = (choice.text or '').strip()
            option_order.append(text)
            if identifier == correct_id:
                key = text
            else:
                distractors.append(text)

        if not key and not distractors:
            continue

        q = Question(
            stem=stem,
            key=key,
            distractors=distractors,
            option_order=option_order,
            difficulty="Medium",
            bloom_level="Understand",
            status="draft",
            created_by="Import",
        )
        questions.append(q)

    return questions


def import_from_moodle_xml(path: Path) -> List[Question]:
    """Import questions from a Moodle XML file.

    Supports the Moodle XML format exported by this app:
    - Root: <quiz> > <question type="multichoice">
    - Each question has questiontext, answers with fractions, generalfeedback, tags.
    """
    tree = ET.parse(path)
    root = tree.getroot()

    questions = []

    # Find all multichoice question elements
    for q_elem in root.findall('.//question[@type="multichoice"]'):
        # Extract stem from questiontext (strip HTML tags)
        stem = ""
        qt_elem = q_elem.find('questiontext')
        if qt_elem is not None:
            text_elem = qt_elem.find('text')
            if text_elem is not None and text_elem.text:
                stem = _strip_html(text_elem.text)

        if not stem:
            continue

        # Extract answers by fraction
        key = ""
        distractors = []
        option_order = []

        for ans_elem in q_elem.findall('answer'):
            fraction = ans_elem.get('fraction', '0')
            text_elem = ans_elem.find('text')
            text = _strip_html(text_elem.text) if text_elem is not None else ""
            if not text:
                continue
            option_order.append(text)
            try:
                frac_val = float(fraction)
            except (ValueError, TypeError):
                frac_val = 0.0
            if frac_val > 0:
                if not key:
                    key = text
                # For multi-select support in the future, additional keys
                # could be tracked here
            else:
                distractors.append(text)

        if not key and not distractors:
            continue

        # Extract explanation from generalfeedback
        explanation = ""
        gf_elem = q_elem.find('generalfeedback')
        if gf_elem is not None:
            gf_text = gf_elem.find('text')
            if gf_text is not None and gf_text.text:
                explanation = _strip_html(gf_text.text)

        # Extract topic from tags
        topic = ""
        tags_elem = q_elem.find('tags')
        if tags_elem is not None:
            tag_elem = tags_elem.find('tag')
            if tag_elem is not None:
                tag_text = tag_elem.find('text')
                if tag_text is not None and tag_text.text:
                    topic = tag_text.text.strip()

        q = Question(
            stem=stem,
            key=key,
            distractors=distractors,
            option_order=option_order,
            explanation=explanation,
            topic=topic,
            difficulty="Medium",
            bloom_level="Understand",
            status="draft",
            created_by="Import",
        )
        questions.append(q)

    return questions

